### ISSUE TITLE
android_external_chromium-webview

### ISSUE THREAD

**Issue by Exodusnick** [danielk43/android_external_chromium-webview#1]
please go back to Webview 96.0.4664.183
there are problems with the current version , all apps that require Webview will crash .
z.B. K9-Mail, Android Browser, Nextcloud News, ...

see here https://github.com/bromite/bromite/issues/1801

**Comment by Exodusnick** [comment]
oh you have already undone it ...
thank you

**Comment by danielk43** [comment]
Noticed the issue yesterday but hadn't pushed yet.. thanks for reporting and pardon the delay

**Comment by Exodusnick** [comment]
no problem ;)

**Comment by danielk43** [comment]
Hi @Exodusnick, so FYI the v97+ versions are actually working fine. You have to enable the new package name, [like so](https://github.com/danielk43/android_vendor_lineage/commit/1313a7a36ae6f67bbe91a4f502d2cc57f87d0e8a) in lineageos. [This](https://github.com/bromite/bromite/wiki/Installing-SystemWebView) page provided the clues.

![Screenshot_20220222-230100_Settings](https://user-images.githubusercontent.com/11856117/155260362-de91437c-5f6d-4248-992f-b2455bc52f3f.png)

**Comment by Exodusnick** [comment]
were you able to successfully create a build ?

https://github.com/danielk43/android_vendor_partner_gms

**Comment by danielk43** [comment]
yep, now including the new package list like [this](https://github.com/danielk43/android_vendor_lineage/commit/fc13d04166301d47d4a027588d4f4ae9ac517141#diff-0733eb4ecce10593169d20be2244fba462ee1bca6b7cba78a13018d17ac98129R62)

**Comment by Exodusnick** [comment]
ok thanks for the tip .
I hope it runs with me this time through 
I only got to this point the other day. :see 
lineage-19.0-20220219-microG-signed-hero2lte.log
https://github.com/lineageos4microg/docker-lineage-cicd/pull/269#issuecomment-1046240339

**Comment by danielk43** [comment]
Hh interesting, hm yeah idk if it's relevant but for LOS 19 I have been using their Permissions repo with the signature spoofing patch from LOS 18 applied. It has always worked and I haven't ever tried with the default settings.

See if [this](https://github.com/danielk43/android_packages_modules_Permission/commit/eca8f44a3e05e36804fda4e9d16f7ad71cb5f629) works for your build

**Comment by Exodusnick** [comment]
see 
https://www.toptal.com/developers/hastebin/dubugicaye.yaml

**Comment by danielk43** [comment]
That one is solved, see the latest commit in the gms repo.
Now seeing problems with vendor.lineage.power@1.0 for your device (hero2lte)

Will look into it later

**Comment by Exodusnick** [comment]
ok thank you very much , also that you help me to solve the problem

**Comment by Exodusnick** [comment]
another information I received from Ivan_Meler ,
maybe helpful for you!
many things have to be undone per revert

https://review.lineageos.org/q/topic:twelve-kill-lineageperf

and repo pick i need to use as well:
https://review.lineageos.org/c/LineageOS/android_system_bpf/+/320591 https://review.lineageos.org/c/LineageOS/android_system_netd/+/320592

to start the build, since 3.18 kernels do not have ebpf support and this has not been ported to a 3.18 kernel yet

the whole thing is very complicated for me ,
because I work with Docker run.sh over linux mint ,
and after syncing branch repository
it has to be fast and revert and pick everything before the build is started .
here my current log

[lineage-19.0-20220227-microG-signed-herolte.log](https://github.com/danielk43/android_external_chromium-webview/files/8148452/lineage-19.0-20220227-microG-signed-herolte.log)

i think you don't need the local_manifests if you do i can send it to you.

i will now start a new build with the changes you made in the gms repo.

**Comment by danielk43** [comment]
OK nice, I think we are on the same page as I was using all of the lineage-19.0 branches in his 8890q projects to get as far as possible yesterday.

If you look under these repos there are files with rows like these -

in android_hardware_samsung:
`hidl/power/Power.h:23:#include <vendor/lineage/power/1.0/ILineagePower.h>`
`hidl/powershare/PowerShare.h:21:#include <vendor/lineage/powershare/1.0/IPowerShare.h>`

in android_device_samsung_universal8890-common:
`hardware/power/Power.h:23:#include <vendor/lineage/power/1.0/ILineagePower.h>`

But there are no vendor/lineage/power* paths available and `ILineagePower.h` doesn't exist in the Lineage source at all. If you mount the images in the unofficial builds [here](https://forum.xda-developers.com/t/lineageos-19-0-android-12-signature-spoofing-for-s7-exynos.4368995/) then the libraries (and other items missing from the repos) are visible under system_ext

```bash
~/Desktop/hero2lte-los19/system$ find ./system/system_ext/ -name "*.so" 2>/dev/null
./system/system_ext/lib64/vendor.lineage.fastcharge@1.0.so
./system/system_ext/lib64/android.hardware.graphics.composer@2.1-resources.so
./system/system_ext/lib64/vendor.lineage.trust@1.0.so
./system/system_ext/lib64/vendor.lineage.power@1.0.so
./system/system_ext/lib64/android.hardware.radio.config@1.2.so
./system/system_ext/lib64/libncurses.so
./system/system_ext/lib64/android.hardware.radio.config@1.1.so
./system/system_ext/lib64/vendor.lineage.touch@1.0.so
./system/system_ext/lib64/vendor.lineage.livedisplay@2.0.so
./system/system_ext/lib64/vendor.lineage.livedisplay@2.1.so
./system/system_ext/lib/android.hardware.radio.config@1.2.so
./system/system_ext/lib/android.hardware.radio.config@1.1.so
```

I haven't looked at the logs you posted yet. Will read soon. I don't think there are too many missing pieces left.

**Comment by danielk43** [comment]
Trying the power submodule step...

**Comment by Exodusnick** [comment]
> another information I received from Ivan_Meler , maybe helpful for you! many things have to be undone per revert
> 
> https://review.lineageos.org/q/topic:twelve-kill-lineageperf
> 
> and repo pick i need to use as well: to start the build, since 3.18 kernels do not have ebpf support and this has not been ported to a 3.18 kernel yet https://review.lineageos.org/c/LineageOS/android_system_bpf/+/320591 https://review.lineageos.org/c/LineageOS/android_system_netd/+/320592
> 
> and this , i have manually inserted this into my local repo hardware/lineage/interfaces/power 1.0 and aidl. [LineageOS/android_hardware_lineage_interfaces@bf1967c](https://github.com/LineageOS/android_hardware_lineage_interfaces/commit/bf1967cd88e766ff59836caaf940ec6526815068)
> 
> the whole thing is very complicated for me , because I work with Docker run.sh over linux mint , and after syncing branch repository it has to be fast and revert and pick everything before the build is started . here my current log
> 
> [lineage-19.0-20220227-microG-signed-herolte.log](https://github.com/danielk43/android_external_chromium-webview/files/8148452/lineage-19.0-20220227-microG-signed-herolte.log)
> 
> i think you don't need the local_manifests if you do i can send it to you.
> 
> i will now start a new build with the changes you made in the gms repo.

I do not know now if I have understood you correctly because I do not understand English properly.
I use [DeepL Translator](https://www.deepl.com/translator) and it does not translate correctly in my german language.

what is strange is that I can create a normal build without microg like ivan_meler.

**Comment by Exodusnick** [comment]
I think you are my saviour I am over 75% now.😉
The error was at 65%

**Comment by danielk43** [comment]
Did it work?

Your translations are fine, thanks for the tips. I will try the cherry-picks.
Good luck, let me know if your build succeeds!

**Comment by danielk43** [comment]
It built! Without the details you mentioned I would not have known how to:

Restore the power config
Revert the perf profile deletion
Make the bpf and netd changes

Thanks for that information.
Here is my copy if you're interested, including all microg modificatons.
Signed with test keys only.

[lineage-19.0-20220227-UNOFFICIAL-hero2lte.zip](https://www.mediafire.com/file/oga18qbpshy1imz/lineage-19.0-20220227-UNOFFICIAL-hero2lte.zip/file)
[boot.img](https://www.mediafire.com/file/nylhuskihrv5ynd/boot.img/file)

**Comment by Exodusnick** [comment]
OK great that it worked for you 👍 unfortunately my build did not run through to the end.
I will send you the log file later.

**Comment by danielk43** [comment]
I posted another build in which I removed all the google repos from roomservice.xml before running brunch in case they might cause interference.

Also created some crude [automation](https://github.com/danielk43/android_hardware_samsung/blob/lineage-19.0/scripts/hero2lte-los19.sh) to toggle between the samsung build and apply/clean up all the git reverts and patches. Right now the controls are bad, you have to run it from the project root like:

```bash
. hardware/samsung/scripts/hero2lte-los19.sh
. hardware/samsung/scripts/hero2lte-los19.sh -c
. hardware/samsung/scripts/hero2lte-los19.sh
. hardware/samsung/scripts/hero2lte-los19.sh -f
. hardware/samsung/scripts/hero2lte-los19.sh
. hardware/samsung/scripts/hero2lte-los19.sh -r
. hardware/samsung/scripts/hero2lte-los19.sh
. hardware/samsung/scripts/hero2lte-los19.sh -p
```

I'll fix it after some sleep.. send your logs when you can

**Comment by Exodusnick** [comment]
sorry I do not quite understand what I have to do now.
I also think that you build differently than how I do.

I go to the folder microg start terminal and run my docker run 19.1.sh then everything starts automatically.

(docker run 19.1.sh)

`docker run \
    -e "BRANCH_NAME=lineage-19.0" \
    -e "DEVICE_LIST=herolte,hero2lte" \
    -e "SIGN_BUILDS=true" \
    -e "WITH_SU=false" \
    -e "SIGNATURE_SPOOFING=yes" \
    -e "UNIFIEDNLP_SUPPORT=true" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore AuroraDroid AuroraServices AuroraStore PdfViewer LocalGsmNlpBackend NominatimNlpBackend NominatimGeocoderBackend FDroid FDroidPrivilegedExtension" \
    -e "WITH_GMS=true" \
    -e "RELEASE_TYPE=microG-signed" \
    -e "INCLUDE_PROPRIETARY=false" \
    -v "/home/exodusnick/lineageos_microG/19.1_microG/lineage:/srv/src" \
    -v "/home/exodusnick/lineageos_microG/19.1_microG/zips:/srv/zips" \
    -v "/home/exodusnick/lineageos_microG/19.1_microG/logs:/srv/logs" \
    -v "/home/exodusnick/lineageos_microG/19.1_microG/cache:/srv/ccache" \
    -v "/home/exodusnick/lineageos_microG/19.1_microG/keys:/srv/keys" \
    -v "/home/exodusnick/lineageos_microG/19.1_microG/manifests:/srv/local_manifests" \
    lineageos4microg/docker-lineage-cicd:lineage-19.0`

`exodusnick@exodusnick:~/lineageos_microG/19.1_microG$ '/home/exodusnick/lineageos_microG/19.1_microG/docker run 19.1.sh' 
Set cache size limit to 50.0 GB
>> [Mon Feb 28 16:07:58 UTC 2022] Branch:  lineage-19.0
>> [Mon Feb 28 16:07:58 UTC 2022] Devices: herolte,herolte,
>> [Mon Feb 28 16:08:01 UTC 2022] (Re)initializing branch repository
>> [Mon Feb 28 16:08:01 UTC 2022] Copying '/srv/local_manifests/*.xml' to '.repo/local_manifests/'
>> [Mon Feb 28 16:08:01 UTC 2022] Syncing branch repository
>> [Mon Feb 28 16:09:40 UTC 2022] Applying the standard signature spoofing patch (android_frameworks_base-S.patch) to frameworks/base
>> [Mon Feb 28 16:09:40 UTC 2022] WARNING: the standard signature spoofing patch introduces a security threat
>> [Mon Feb 28 16:09:40 UTC 2022] Applying the modules/Permission patch (packages_modules_Permission-S.patch) to packages/modules/Permission
>> [Mon Feb 28 16:09:40 UTC 2022] Setting "microG-signed" as release type
>> [Mon Feb 28 16:09:40 UTC 2022] Adding OTA URL overlay (for custom URL )
>> [Mon Feb 28 16:09:40 UTC 2022] Adding custom packages (GmsCore GsfProxy FakeStore AuroraDroid AuroraServices AuroraStore PdfViewer LocalGsmNlpBackend NominatimNlpBackend NominatimGeocoderBackend FDroid FDroidPrivilegedExtension)
>> [Mon Feb 28 16:09:40 UTC 2022] Adding keys path (/srv/keys)
>> [Mon Feb 28 16:09:40 UTC 2022] Preparing build environment
>> [Mon Feb 28 16:09:48 UTC 2022] Starting build for herolte, lineage-19.0 branch
`
no changes were made in the sources 
what do you mean by 

hardware/samsung/scripts/hero2lte-los19.sh
. hardware/samsung/scripts/hero2lte-los19.sh -c
. hardware/samsung/scripts/hero2lte-los19.sh
. hardware/samsung/scripts/hero2lte-los19.sh -f
. hardware/samsung/scripts/hero2lte-los19.sh
. hardware/samsung/scripts/hero2lte-los19.sh -r
. hardware/samsung/scripts/hero2lte-los19.sh
. hardware/samsung/scripts/hero2lte-los19.sh -p

**Comment by danielk43** [comment]
I am building differently, the docker-lineage-cicd scripts have changed a lot since I used them most recently for Android 10. A couple things: you don't need both Aurora* and FDroid* packages. I am also not adding an OTA overlay (yet) but neither of those should make a difference.

The commands I pasted will automatically apply/remove the reverts and patches we were talking about yesterday:
https://review.lineageos.org/q/topic:twelve-kill-lineageperf
https://review.lineageos.org/c/LineageOS/android_system_bpf/+/320591 https://review.lineageos.org/c/LineageOS/android_system_netd/+/320592
https://github.com/LineageOS/android_hardware_lineage_interfaces/commit/bf1967cd88e766ff59836caaf940ec6526815068

-r and -p apply, -c and -f clean up: it's faster than doing it manually, my 0228 build was done using the script to patch.

I'm curious when/how your build is failing. Please send the entire most recent build log

**Comment by danielk43** [comment]
Also can I see your local manifest please

**Comment by Exodusnick** [comment]
a ok now I understand what you meant by that 
-r and -p apply, -c and -f clean up.

you always learn something new ;)
i was also amazed what you wrote in the scripts i only understand half of .......
as you read him my github profile surely learn C++ with SoloLearn. that since 1 year , but it is difficult for me because I do not understand english well.

I want to thank you again for your help 

Yes, I'll send you the build log complete with the next error . I hope none comes ;)

 the repo from ivan is not the problem the problem is the revert and cherry pick because once dockers.sh is executed everything resets back to the original state of ivans repo 
see [Mon Feb 28 16:08:01 UTC 2022] Syncing branch repository
and when that comes see [Mon Feb 28 16:09:40 UTC 2022] Preparing build environment
I apply all revert and all cherry pick .
and probably I am too slow to Starting build for herolte, lineage-19.0 branch........

[local_manifests.zip](https://github.com/danielk43/android_external_chromium-webview/files/8155934/local_manifests.zip)

**Comment by Exodusnick** [comment]
"breakfast" or "brunch" 
that makes the doker run.sh automatic start it ...
see [Mon Feb 28 16:08:01 UTC 2022] Copying '/srv/local_manifests/*.xml' to '.repo/local_manifests/'

**Comment by danielk43** [comment]
Thanks, it's not a problem. I have only been building for a few google devices and been meaning to learn more about other vendors so it's my pleasure to help out and learn something new myself.

You've got the right idea in your local manifests using remove-project. Let me take a closer look and I will suggest something soon, once it's more clear what the best path forward is. Possibly even modifying docker-lineage-cicd.

**Comment by Exodusnick** [comment]
the idea of docker-lineage-cicd i had also but that didn't work .i had it fok and replaced it with the 
replaced exodusnick/docker-lineage-cicd:lineage-19.0
and then tried to start the docker run 19.1.sh and then came (no permissions) 
that means i have no permission on docker-lineage-cicd .
because I only use lokal on pc the docker run.sh.

if docker-lineage-cicd is changed then only via 
lineageos4microg/docker-lineage-cicd:lineage-19.0
so I have no problems because I can then docker pull lineageos4microg/docker-lineage-cicd:lineage-19.0 run that it is updated with me.

**Comment by Exodusnick** [comment]
too bad failed again :-1: 
[lineage-19.0-20220228-microG-signed-herolte.log](https://github.com/danielk43/android_external_chromium-webview/files/8161818/lineage-19.0-20220228-microG-signed-herolte.log)

**Comment by danielk43** [comment]
OK

```
error: non-static method getRequestedFakeSignature(AndroidPackage) cannot be referenced from a static context
                    String sig = getRequestedFakeSignature(p);
```

This happened to me when I tried to use the signature spoofing patch for 11 on a 12 build. Rework your S patch like [this](https://github.com/microg/GmsCore/pull/1586/files) plus the Permissions package update mentioned earlier ([this](https://github.com/danielk43/android_packages_modules_Permission/commit/eca8f44a3e05e36804fda4e9d16f7ad71cb5f629) one). But you might be applying permissions already 

If you're getting to 99% then maybe this will be the last issue!

**Comment by Exodusnick** [comment]
>> [Tue Mar  1 13:32:11 UTC 2022] Applying the standard signature spoofing patch (android_frameworks_base-S.patch) to frameworks/base
>> [Tue Mar  1 13:32:11 UTC 2022] WARNING: the standard signature spoofing patch introduces a security threat
>> [Tue Mar  1 13:32:11 UTC 2022] Applying the modules/Permission patch (packages_modules_Permission-S.patch) to packages/modules/Permission
this comes directly from 
https://github.com/lineageos4microg/docker-lineage-cicd/blob/lineage-19.0/src/signature_spoofing_patches/android_frameworks_base-S.patch

**Comment by Exodusnick** [comment]
see here https://github.com/lineageos4microg/docker-lineage-cicd/issues/243

**Comment by Exodusnick** [comment]
the s pacht is equal ....
and this is also present in my local sources  ([this](https://github.com/danielk43/android_packages_modules_Permission/commit/eca8f44a3e05e36804fda4e9d16f7ad71cb5f629) ).

**Comment by danielk43** [comment]
yup! Nice find, that should do it

**Comment by danielk43** [comment]
And would explain why there were already 19.0 builds working

**Comment by Exodusnick** [comment]
> OK
> 
> ```
> error: non-static method getRequestedFakeSignature(AndroidPackage) cannot be referenced from a static context
>                     String sig = getRequestedFakeSignature(p);
> ```
> 
> This happened to me when I tried to use the signature spoofing patch for 11 on a 12 build. Rework your S patch like [this](https://github.com/microg/GmsCore/pull/1586/files) plus the Permissions package update mentioned earlier ([this](https://github.com/danielk43/android_packages_modules_Permission/commit/eca8f44a3e05e36804fda4e9d16f7ad71cb5f629) one). But you might be applying permissions already
> 
> If you're getting to 99% then maybe this will be the last issue!



> OK
> 
> ```
> error: non-static method getRequestedFakeSignature(AndroidPackage) cannot be referenced from a static context
>                     String sig = getRequestedFakeSignature(p);
> ```
> 
> This happened to me when I tried to use the signature spoofing patch for 11 on a 12 build. Rework your S patch like [this](https://github.com/microg/GmsCore/pull/1586/files) plus the Permissions package update mentioned earlier ([this](https://github.com/danielk43/android_packages_modules_Permission/commit/eca8f44a3e05e36804fda4e9d16f7ad71cb5f629) one). But you might be applying permissions already
> 
> If you're getting to 99% then maybe this will be the last issue!

Have the same problem again abort at 99%.
I will now use yours

**Comment by Exodusnick** [comment]
sorry other error see log 
https://www.toptal.com/developers/hastebin/vevuvefogo.kotlin

**Comment by danielk43** [comment]
Unfortunately I have not seen that one yet.. Looking now and I will try to build later using docker-lineage-cicd

**Comment by danielk43** [comment]
The only thing I can think of immediately is that your frameworks/base repo might be modified. Are you getting the identical output?

```
lineage-19.0$ grep -IHnr 'cleanupProximity'
frameworks/base/services/core/java/com/android/server/power/PowerManagerService.java:5055:                    cleanupProximity();
frameworks/base/services/core/java/com/android/server/power/PowerManagerService.java:6470:    private void cleanupProximity() {
frameworks/base/services/core/java/com/android/server/power/PowerManagerService.java:6472:            cleanupProximityLocked();
frameworks/base/services/core/java/com/android/server/power/PowerManagerService.java:6476:    private void cleanupProximityLocked() {
frameworks/base/services/core/java/com/android/server/power/PowerManagerService.java:6516:                    cleanupProximityLocked();
lineage-19.0$ grep -IHnr 'runWithProximityCheck'
frameworks/base/services/core/java/com/android/server/power/PowerManagerService.java:5567:                runWithProximityCheck(r);
frameworks/base/services/core/java/com/android/server/power/PowerManagerService.java:6486:    private void runWithProximityCheck(final Runnable r) {
```
is `cd frameworks/base && git status` returning anything unexpected?

**Comment by Exodusnick** [comment]
exodusnick@exodusnick:~/lineageos_microG/19.1_microG/lineage/LINEAGE_19_0/frameworks/base$ grep -IHnr 'cleanupProximity'
services/core/java/com/android/server/power/PowerManagerService.java:5056:                    cleanupProximity();
services/core/java/com/android/server/power/PowerManagerService.java:6481:    private void cleanupProximity() {
services/core/java/com/android/server/power/PowerManagerService.java:6483:            cleanupProximityLocked();
services/core/java/com/android/server/power/PowerManagerService.java:6487:    private void cleanupProximityLocked() {
services/core/java/com/android/server/power/PowerManagerService.java:6527:                    cleanupProximityLocked();
exodusnick@exodusnick:~/lineageos_microG/19.1_microG/lineage/LINEAGE_19_0/frameworks/base$ grep -IHnr 'runWithProximityCheck'
services/core/java/com/android/server/power/PowerManagerService.java:5568:                runWithProximityCheck(r);
services/core/java/com/android/server/power/PowerManagerService.java:6497:    private void runWithProximityCheck(final Runnable r) {
exodusnick@exodusnick:~/lineageos_microG/19.1_microG/lineage/LINEAGE_19_0/frameworks/base$ 
``

**Comment by Exodusnick** [comment]
exodusnick@exodusnick:~/lineageos_microG/19.1_microG/lineage/LINEAGE_19_0/frameworks/base$ grep -IHnr 'cleanupProximity'
services/core/java/com/android/server/power/PowerManagerService.java:5056:                    cleanupProximity();
services/core/java/com/android/server/power/PowerManagerService.java:6481:    private void cleanupProximity() {
services/core/java/com/android/server/power/PowerManagerService.java:6483:            cleanupProximityLocked();
services/core/java/com/android/server/power/PowerManagerService.java:6487:    private void cleanupProximityLocked() {
services/core/java/com/android/server/power/PowerManagerService.java:6527:                    cleanupProximityLocked();
exodusnick@exodusnick:~/lineageos_microG/19.1_microG/lineage/LINEAGE_19_0/frameworks/base$ grep -IHnr 'runWithProximityCheck'
services/core/java/com/android/server/power/PowerManagerService.java:5568:                runWithProximityCheck(r);
services/core/java/com/android/server/power/PowerManagerService.java:6497:    private void runWithProximityCheck(final Runnable r) {
exodusnick@exodusnick:~/lineageos_microG/19.1_microG/lineage/LINEAGE_19_0/frameworks/base$

**Comment by danielk43** [comment]
Hm nothing to commit but the defintions are on a different row. Just as a debug step you could try building with my frameworks/base and `-e "SIGNATURE_SPOOFING=no"` since it is already applied on the fork

**Comment by danielk43** [comment]
I managed to get a build working in the container, just with my projects again. I replaced the official android repo with my fork, moved the patch script functions into the docker image (where they are working perfectly), and added an environment variable called HEROLTE to run the patches and cleanup, like [this](https://github.com/danielk43/docker-lineage-cicd/commit/a7035a3f40c997bc7123be46b1948048171e2ee6)

So first I am building the docker image from my branch locally:
```bash
docker-lineage-cicd$ docker build -t danielk43/docker-lineage-cicd:lineage-19.0-8890 .
```

Then running the command like:
```
docker-lineage-cicd$ docker run \
-e "BRANCH_NAME=lineage-19.0" \
-e "DEVICE_LIST=herolte,hero2lte" \
-e "CCACHE_SIZE=100G" \
-e "SIGN_BUILDS=true" \
-e "SIGNATURE_SPOOFING=no" \
-e "WITH_GMS=false" \
-e "RELEASE_TYPE=microG-test" \
-e "INCLUDE_PROPRIETARY=false" \
-e "HEROLTE=true" \
-v "/media/daniel/TEAM_2TB:/srv/src" \
-v "/home/daniel/android/ROMs/lineageos:/srv/zips" \
-v "/home/daniel/android/ROMs/lineageos/logs:/srv/logs" \
-v "/mnt/ccache:/srv/ccache" \
-v "/media/daniel/TEAM_2TB/lineage-19.0/keys/lineage:/srv/keys" \
danielk43/docker-lineage-cicd:lineage-19.0-8890
```

In my case, SIGNATURE_SPOOFING is "no" because those changes are already included, and WITH_GMS is false and CUSTOM_PACKAGES is empty because that's what [this](https://github.com/danielk43/android_vendor_lineage/commit/fc13d04166301d47d4a027588d4f4ae9ac517141#diff-0733eb4ecce10593169d20be2244fba462ee1bca6b7cba78a13018d17ac98129R62) is doing.

Then I get nice output, note the rows with the samsung patching because I used $HEROLTE:
```
Set cache size limit to 100.0 GB
>> [Thu Mar  3 04:39:52 UTC 2022] Branch:  lineage-19.0
>> [Thu Mar  3 04:39:52 UTC 2022] Devices: herolte,hero2lte,
>> [Thu Mar  3 04:39:53 UTC 2022] (Re)initializing branch repository
>> [Thu Mar  3 04:39:54 UTC 2022] Copying '/srv/local_manifests/*.xml' to '.repo/local_manifests/'
>> [Thu Mar  3 04:39:54 UTC 2022] Syncing branch repository
>> [Thu Mar  3 04:41:14 UTC 2022] Setting "microG-test" as release type
>> [Thu Mar  3 04:41:14 UTC 2022] Adding OTA URL overlay (for custom URL )
>> [Thu Mar  3 04:41:14 UTC 2022] Adding keys path (/srv/keys)
>> [Thu Mar  3 04:41:14 UTC 2022] Preparing build environment
>> [Thu Mar  3 04:41:26 UTC 2022] Patching Samsung 8890 LineageOS source
>> [Thu Mar  3 04:41:39 UTC 2022] Starting build for herolte, lineage-19.0 branch
>> [Thu Mar  3 05:14:09 UTC 2022] Moving build artifacts for herolte to '/srv/zips/herolte'
>> [Thu Mar  3 05:14:11 UTC 2022] Finishing build for herolte
>> [Thu Mar  3 05:14:11 UTC 2022] Cleaning source dir for device herolte
>> [Thu Mar  3 05:14:54 UTC 2022] Patching Samsung 8890 LineageOS source
>> [Thu Mar  3 05:15:18 UTC 2022] Starting build for hero2lte, lineage-19.0 branch
>> [Thu Mar  3 06:04:14 UTC 2022] Moving build artifacts for hero2lte to '/srv/zips/hero2lte'
>> [Thu Mar  3 06:04:16 UTC 2022] Finishing build for hero2lte
>> [Thu Mar  3 06:04:16 UTC 2022] Cleaning source dir for device hero2lte
```

I tried to add back gesture input, where you can type without lifting your finger off the screen. No idea if it works on Samsung.
Here are the files from this time, tomorrow I will try to use the official source where possible and see if it can finish.

[lineage-19.0-20220303-microG-test-herolte](https://www.mediafire.com/folder/lox5bafqmmqn5)
[lineage-19.0-20220303-microG-test-hero2lte](https://www.mediafire.com/folder/q6klq2g4l4o94)

**Comment by Exodusnick** [comment]
Wow thank you👍

**Comment by Exodusnick** [comment]
I will also test it today with your settings.
Thank you very much for the help.

**Comment by Exodusnick** [comment]
exodusnick@exodusnick:~/lineageos_microG/19.1_microG$ '/home/exodusnick/lineageos_microG/19.1_microG/docker run 19.1.sh' 
Unable to find image 'danielk43/docker-lineage-cicd:lineage-19.0-8890' locally
docker: Error response from daemon: pull access denied for danielk43/docker-lineage-cicd, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

too bad , i can't use your danielk43/docker-lineage-cicd:lineage-19.0-8890 in my docker run 19.0.sh

**Comment by danielk43** [comment]
You can build it! So if that is my fork of `docker-lineage-cicd` then just

```bash
cd /path/to/docker-lineage-cicd
git checkout lineage-19.0-8890
docker build -t danielk43/docker-lineage-cicd:lineage-19.0-8890 .
```

then the image will be found locally when you mention it in `docker run`

**Comment by Exodusnick** [comment]
i do not understand .
I do not have a folder called cd /path/to/docker-lineage-cicd.
i only run my docker run 19.0.sh on my pc in /home/exodusnick/lineageos_microG/19.1_microG.

**Comment by Exodusnick** [comment]
do you have maybe the possibility to help me via teamviewer ?

**Comment by danielk43** [comment]
/path/to/docker-lineage-cicd is where you cloned the repo because the `.` at the end of the `docker build` command specifies the location of the Dockerfile which is pwd for the command

```bash
git clone https://github.com/danielk43/docker-lineage-cicd.git
cd docker-lineage-cicd
git checkout lineage-19.9-8890
docker build -t danielk43/docker-lineage-cicd:lineage-19.0-8890 .
```

**Comment by Exodusnick** [comment]
Ok.

**Comment by danielk43** [comment]
Alright, my image is now public. The command should work!

**Comment by Exodusnick** [comment]
> /path/to/docker-lineage-cicd is where you cloned the repo because the `.` at the end of the `docker build` command specifies the location of the Dockerfile which is pwd for the command
> 
> ```shell
> git clone https://github.com/danielk43/docker-lineage-cicd.git
> cd docker-lineage-cicd
> git checkout lineage-19.9-8890
> docker build -t danielk43/docker-lineage-cicd:lineage-19.0-8890 .
> ```

the command works am already all the time on it

**Comment by danielk43** [comment]
Yup, perfect. I'm making some more updates to it now to not depend on the samsung repo, and use kdrag0n's signature spoofing patch (if enabled). But this should build fine, fingers crossed

**Comment by Exodusnick** [comment]
Thanks a lot 
So everything rebuilt took a little longer because I did something wrong in the beginning.
Build was started and everything was added automatically.
Now I am curious whether it runs through with me as with you.
If everything works and everything works then you have something good with me.😉

**Comment by danielk43** [comment]
Best of luck! I actually just now pushed an update to the image which does not lock it to my repo,  you can update with `docker pull danielk43/docker-lineage-cicd:lineage-19.0-8890` .. next time, so your current build isn't interrupted.

There will be some new features which make this way more usable:

REPO_INIT: defaults to LineageOS/android. Set to repo init another github project (like mine, see example)
SKIP_BREAKFAST: defaults to false, may be beneficial to skip when using local manifests for device tree and kernel.

So with the above changes I am now just running like this:
```
docker run \
-e "CCACHE_SIZE=100G" \
-e "BRANCH_NAME=lineage-19.0" \
-e "DEVICE_LIST=herolte,hero2lte" \
-e "INCLUDE_PROPRIETARY=false" \
-e "SIGN_BUILDS=true" \
-e "REPO_INIT=danielk43/android" \
-e "HEROLTE=true" \
-v ...
```

SIGNATURE_SPOOFING and WITH_GMS both default to false so I left them out this time. When not using REPO_INIT these would both be yes/true. You may want to set a different RELEASE_TYPE, at least it is an option. 

Also you don't need your local manifests when using my fork but I don't believe there are any conflicts and it should be ok. Other than that it's been building successfuly every time I've tested it today.

**Comment by Exodusnick** [comment]
I am still building herolte successfully created and working.
hero2lte is still in progress.
as soon as that is ready I will update.
please write me a private mail i want to thank you for the help and send you something everything else we can communicate by mail . 
contact Exodusnick79@gmail.com
would be really happy if you get in contact via mail.
or 
https://forum.los-legacy.de/legal-notice/
